apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: capstone
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_USER: "wordpress_user"
  MYSQL_PASSWORD: "wordpress_pass"
  MYSQL_DATABASE: "wordpress_db"
